fields:
- mode: NULLABLE
  name: client_id
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: client_id
- mode: NULLABLE
  name: sample_id
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: sample_id
- mode: NULLABLE
  name: profile_group_id
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: profile_group_id
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: submission_date
- mode: NULLABLE
  name: metric_date
  type: DATE
  description: Metric Date
- mode: NULLABLE
  name: country
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: country
- mode: NULLABLE
  name: locale
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: top_locales_locale
- mode: NULLABLE
  name: app_version
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: app_version
- mode: NULLABLE
  name: normalized_channel
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: normalized_channel
- mode: NULLABLE
  name: first_seen_date
  type: DATE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: first_seen_date
- mode: NULLABLE
  name: attribution_campaign
  type: STRING
  description: Attribution Campaign
- mode: NULLABLE
  name: attribution_content
  type: STRING
  description: Attribution Content
- mode: NULLABLE
  name: attribution_dlsource
  type: STRING
  description: Attribution DL Source
- mode: NULLABLE
  name: attribution_medium
  type: STRING
  description: Attribution Medium
- mode: NULLABLE
  name: attribution_ua
  type: STRING
  description: Attribution UA
- mode: NULLABLE
  name: attribution_experiment
  type: STRING
  description: Attribution Experiment
- mode: NULLABLE
  name: attribution_variation
  type: STRING
  description: Attribution Variation
- mode: NULLABLE
  name: startup_profile_selection_reason
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: startup_profile_selection_reason
- mode: NULLABLE
  name: normalized_os
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: normalized_os
- mode: NULLABLE
  name: normalized_os_version
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: normalized_os_version
- mode: NULLABLE
  name: distribution_id
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: distribution_id
- mode: NULLABLE
  name: isp
  type: STRING
  description: The name of the internet service provider associated with the client's
    IP address.
- mode: NULLABLE
  name: is_desktop
  type: BOOLEAN
  description: Indicates if the client is included in the desktop KPI
- mode: NULLABLE
  name: days_seen_bits
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: days_seen_bits
- mode: NULLABLE
  name: days_active_bits
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: days_active_bits
- mode: NULLABLE
  name: ping_sent_metric_date
  type: BOOLEAN
  description: Ping Sent on Metric Date
- mode: NULLABLE
  name: ping_sent_week_4
  type: BOOLEAN
  description: Ping Sent Week 4
- mode: NULLABLE
  name: active_metric_date
  type: BOOLEAN
  description: Active on Metric Date
- mode: NULLABLE
  name: retained_week_4
  type: BOOLEAN
  description: Retained Week 4
- mode: NULLABLE
  name: new_profile_metric_date
  type: BOOLEAN
  description: New Profile on Metric Date
- mode: NULLABLE
  name: repeat_profile
  type: BOOLEAN
  description: Repeat Profile
- mode: NULLABLE
  name: retained_week_4_new_profile
  type: BOOLEAN
  description: Retained Week 4 New Profile
