fields:
  - mode: NULLABLE
    name: timestamp
    type: TIMESTAMP
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
      field: timestamp
  - mode: NULLABLE
    name: server
    type: STRING
  - mode: NULLABLE
    name: version
    type: STRING
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
      field: jsonPayload_fields_version
  - mode: NULLABLE
    name: commit
    type: STRING
  - mode: NULLABLE
    name: l10n
    type: STRING
  - mode: NULLABLE
    name: tospp
    type: STRING
  - mode: NULLABLE
    name: since_last_push
    type: FLOAT
