fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/addons_derived/dataset_schema.yaml
    field: submission_date
- name: addon_id
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/addons_derived/dataset_schema.yaml
    field: addon_id
- name: dau
  type: INTEGER
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/addons_derived/dataset_schema.yaml
    field: dau
- name: dau_by_addon_version
  type: RECORD
  mode: REPEATED
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/addons_derived/dataset_schema.yaml
    field: dau_by_addon_version
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
    description: Addon version.
  - name: value
    type: INTEGER
    mode: NULLABLE
    description: DAU count for the corresponding addon version.
- name: dau_by_app_version
  type: RECORD
  mode: REPEATED
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/addons_derived/dataset_schema.yaml
    field: dau_by_app_version
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
    description: App version.
  - name: value
    type: INTEGER
    mode: NULLABLE
    description: DAU count for the corresponding app version.
- name: dau_by_fenix_build
  type: RECORD
  mode: REPEATED
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/addons_derived/dataset_schema.yaml
    field: dau_by_fenix_build
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
    description: Build identifier.
  - name: value
    type: INTEGER
    mode: NULLABLE
    description: DAU count for the corresponding fenix build.
- name: dau_by_locale
  type: RECORD
  mode: REPEATED
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/addons_derived/dataset_schema.yaml
    field: dau_by_locale
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
    description: locale.
  - name: value
    type: INTEGER
    mode: NULLABLE
    description: DAU count for the corresponding locale.
- name: dau_by_country
  type: RECORD
  mode: REPEATED
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/addons_derived/dataset_schema.yaml
    field: dau_by_country
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
    description: Country.
  - name: value
    type: INTEGER
    mode: NULLABLE
    description: DAU count for the corresponding country.
- name: dau_by_app_os
  type: RECORD
  mode: REPEATED
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/addons_derived/dataset_schema.yaml
    field: dau_by_app_os
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
    description: OS.
  - name: value
    type: INTEGER
    mode: NULLABLE
    description: DAU count for the corresponding os.
