fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: submission_date

    Also, used for partitioning the table.

    '
- mode: NULLABLE
  name: days_seen_bits
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: days_seen_bits

    '
- mode: NULLABLE
  name: days_seen_in_tier1_country_bits
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: days_seen_in_tier1_country_bits

    '
- mode: NULLABLE
  name: days_registered_bits
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: days_registered_bits

    '
- mode: NULLABLE
  name: user_id
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: user_id

    User ID (registered user).

    '
- mode: NULLABLE
  name: country
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: country

    See: UDF mozdata.stats.mode_last for more

    info on how the function operates.

    '
- mode: NULLABLE
  name: language
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: language

    '
- mode: NULLABLE
  name: app_version
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: app_version

    follows format: major.minor.patch (e.g. 99.3.3).

    '
- mode: NULLABLE
  name: os_name
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: os_name

    For example: Android.

    '
- mode: NULLABLE
  name: os_version
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: os_version

    '
- mode: NULLABLE
  name: days_seen_no_monitor_bits
  type: INTEGER
  description: 'No. of days since monitor flag was last True.

    '
