fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: submission_date
- name: days_seen_bits
  type: INTEGER
  mode: NULLABLE
- name: days_seen_in_tier1_country_bits
  type: INTEGER
  mode: NULLABLE
- name: days_registered_bits
  type: INTEGER
  mode: NULLABLE
- name: resurrected_same_service
  type: BOOLEAN
  mode: NULLABLE
- name: resurrected_any_service
  type: BOOLEAN
  mode: NULLABLE
- name: user_id
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: jsonPayload_fields_user_id
- name: service
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: jsonPayload_fields_service
- name: country
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: jsonPayload_fields_country
- name: language
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: language
- name: app_version
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: jsonPayload_fields_app_version
- name: os_name
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: jsonPayload_fields_os_name
- name: os_version
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: os_version
