fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: ''
- name: mau
  type: INT64
  mode: NULLABLE
  description: ''
- name: wau
  type: INT64
  mode: NULLABLE
  description: ''
- name: dau
  type: INT64
  mode: NULLABLE
  description: ''
- name: mau_tier1_inclusive
  type: INT64
  mode: NULLABLE
  description: ''
- name: id_bucket
  type: INT64
  mode: NULLABLE
  description: ''
- name: country
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: jsonPayload_fields_country
