fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: ''
- name: window_start
  type: TIMESTAMP
  mode: NULLABLE
  description: ''
- name: channel
  type: STRING
  mode: NULLABLE
  description: ''
- name: version
  type: STRING
  mode: NULLABLE
  description: ''
- name: display_version
  type: STRING
  mode: NULLABLE
  description: ''
- name: build_id
  type: STRING
  mode: NULLABLE
  description: ''
- name: application
  type: STRING
  mode: NULLABLE
  description: ''
- name: os_name
  type: STRING
  mode: NULLABLE
  description: ''
- name: os_version
  type: STRING
  mode: NULLABLE
  description: ''
- name: architecture
  type: STRING
  mode: NULLABLE
  description: ''
- name: country
  type: STRING
  mode: NULLABLE
  description: ''
- name: count
  type: INT64
  mode: NULLABLE
  description: ''
- name: main_crashes
  type: INT64
  mode: NULLABLE
  description: ''
- name: content_crashes
  type: INT64
  mode: NULLABLE
  description: ''
- name: startup_crashes
  type: INT64
  mode: NULLABLE
  description: ''
- name: content_shutdown_crashes
  type: INT64
  mode: NULLABLE
  description: ''
- name: gpu_crashes
  type: INT64
  mode: NULLABLE
  description: ''
- name: plugin_crashes
  type: INT64
  mode: NULLABLE
  description: ''
- name: gmplugin_crashes
  type: INT64
  mode: NULLABLE
  description: ''
- name: usage_hours
  type: FLOAT64
  mode: NULLABLE
  description: ''
