fields:
  - mode: NULLABLE
    name: fetchTime
    type: TIMESTAMP
  - mode: NULLABLE
    name: url
    type: STRING
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
      field: jsonPayload_config_tracing_otel_url
  - mode: NULLABLE
    name: category
    type: STRING
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
      field: category
  - mode: NULLABLE
    name: audit
    type: STRING
  - mode: NULLABLE
    name: score
    type: NUMERIC
  - mode: NULLABLE
    name: numVal
    type: NUMERIC
  - mode: NULLABLE
    name: formfactor
    type: STRING
