fields:
- name: HAPPENED_AT
  type: DATE
  mode: NULLABLE
  description: ''
- name: TILE_ID
  type: INT64
  mode: NULLABLE
  description: ''
- name: POSITION
  type: INT64
  mode: NULLABLE
  description: ''
- name: IMPRESSION_COUNT
  type: INT64
  mode: NULLABLE
  description: ''
- name: CLICK_COUNT
  type: INT64
  mode: NULLABLE
  description: ''
- name: SAVE_COUNT
  type: INT64
  mode: NULLABLE
  description: ''
- name: DISMISS_COUNT
  type: INT64
  mode: NULLABLE
  description: ''
- name: _GS_FILE_NAME
  type: STRING
  mode: NULLABLE
  description: ''
- name: _GS_FILE_ROW_NUMBER
  type: INT64
  mode: NULLABLE
  description: ''
- name: _GS_FILE_DATE
  type: STRING
  mode: NULLABLE
  description: ''
- name: _GS_FILE_TIME
  type: STRING
  mode: NULLABLE
  description: ''
- name: _LOADED_AT
  type: INT64
  mode: NULLABLE
  description: ''
