fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: submission_date
- mode: NULLABLE
  name: client_id
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: client_id
- mode: NULLABLE
  name: default_search_engine
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: default_search_engine
- mode: NULLABLE
  name: app_version
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: app_version
- mode: NULLABLE
  name: normalized_channel
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: normalized_channel
- mode: NULLABLE
  name: country
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: country
- mode: NULLABLE
  name: locale
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: top_locales_locale
- mode: NULLABLE
  name: search_region
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: search_region
- mode: NULLABLE
  name: suggest_enabled
  type: BOOLEAN
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: suggest_enabled
- mode: NULLABLE
  name: in_navbar
  type: BOOLEAN
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: in_navbar
- mode: NULLABLE
  name: suggest_searches
  type: BOOLEAN
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: suggest_searches
- mode: NULLABLE
  name: show_search_suggestions_first
  type: BOOLEAN
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: show_search_suggestions_first
- mode: NULLABLE
  name: suggest_quicksuggest
  type: BOOLEAN
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: suggest_quicksuggest
- mode: NULLABLE
  name: suggest_quicksuggest_sponsored
  type: BOOLEAN
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: suggest_quicksuggest_sponsored
- mode: NULLABLE
  name: quicksuggest_onboarding_dialog_choice
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: quicksuggest_onboarding_dialog_choice
- mode: NULLABLE
  name: count_picked_total
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: count_picked_total
- fields:
  - mode: NULLABLE
    name: key
    type: STRING
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
      field: experiments_key
  - mode: NULLABLE
    name: value
    type: INTEGER
  mode: REPEATED
  name: count_picked_by_type
  type: RECORD
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: count_picked_by_type
- fields:
  - mode: NULLABLE
    name: key
    type: INTEGER
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
      field: experiments_key
  - mode: NULLABLE
    name: value
    type: INTEGER
  mode: REPEATED
  name: count_picked_by_position
  type: RECORD
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: count_picked_by_position
- fields:
  - mode: NULLABLE
    name: type
    type: STRING
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
      field: active_addons_type
  - fields:
    - mode: NULLABLE
      name: key
      type: INTEGER
      description: !include-field-description
        file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
        field: experiments_key
    - mode: NULLABLE
      name: value
      type: INTEGER
    mode: REPEATED
    name: position
    type: RECORD
  mode: REPEATED
  name: urlbar_picked_by_type_by_position
  type: RECORD
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: urlbar_picked_by_type_by_position
- mode: NULLABLE
  name: suggest_quicksuggest_nonsponsored
  type: BOOLEAN
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: suggest_quicksuggest_nonsponsored
- mode: NULLABLE
  name: quicksuggest_data_collection_enabled
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: quicksuggest_data_collection_enabled
- fields:
  - mode: NULLABLE
    name: key
    type: STRING
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
      field: experiments_key
  - mode: NULLABLE
    name: value
    type: STRING
  mode: REPEATED
  name: experiments
  type: RECORD
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: experiments
- mode: NULLABLE
  name: profile_group_id
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: profile_group_id
