fields:
- mode: NULLABLE
  name: first_seen_date
  type: DATE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: first_seen_date
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: submission_date
- mode: NULLABLE
  name: app_version
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: app_version
- mode: NULLABLE
  name: architecture
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: architecture
- mode: NULLABLE
  name: attribution_campaign
  type: STRING
  description: The campaign this client's install was attributed to, identifying a specific marketing campaign or promotion.
- mode: NULLABLE
  name: attribution_content
  type: STRING
  description: The attribution content identifier; similar to UTM content, indicating the particular link or creative within a campaign.
- mode: NULLABLE
  name: attribution_experiment
  type: STRING
  description: The attribution experiment key associated with the client's install, identifying a download-funnel experiment.
- mode: NULLABLE
  name: attribution_medium
  type: STRING
  description: The attribution medium; similar to UTM medium, indicating the category of traffic source (e.g., 'referral', 'paidsearch').
- mode: NULLABLE
  name: attribution_source
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: attribution_source
- mode: NULLABLE
  name: attribution_ua
  type: STRING
  description: The browser user-agent used to download Firefox, indicating the browser the client was using prior to installation (e.g., 'chrome', 'edge',
    'firefox').
- mode: NULLABLE
  name: partner_distribution_version
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: partner_distribution_version
- mode: NULLABLE
  name: partner_distributor
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: partner_distributor
- mode: NULLABLE
  name: partner_distributor_channel
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: partner_distributor_channel
- mode: NULLABLE
  name: partner_id
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: partner_id
- mode: NULLABLE
  name: platform_version
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: platform_version
- mode: NULLABLE
  name: city
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: city
- mode: NULLABLE
  name: subdivision1
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: subdivision1
- mode: NULLABLE
  name: country
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: country
- mode: NULLABLE
  name: db_version
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: db_version
- mode: NULLABLE
  name: distribution_id
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: distribution_id
- mode: NULLABLE
  name: locale
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: top_locales_locale
- mode: NULLABLE
  name: normalized_app_name
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: normalized_app_name
- mode: NULLABLE
  name: normalized_channel
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: normalized_channel
- mode: NULLABLE
  name: normalized_os
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: normalized_os
- mode: NULLABLE
  name: normalized_os_version
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: normalized_os_version
- mode: NULLABLE
  name: startup_profile_selection_reason
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: startup_profile_selection_reason
- mode: NULLABLE
  name: vendor
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: vendor
- mode: NULLABLE
  name: os_version_major
  type: INTEGER
  description: Major or first part of the operating system version running at the
    client. E.g. for version "100.9.11", the major is 100.
- mode: NULLABLE
  name: os_version_minor
  type: INTEGER
  description: Minor part of the operating system version running at the client. E.g.
    for version "100.9.11", the minor is 9.
- mode: NULLABLE
  name: num_clients_in_cohort
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: num_clients_in_cohort
- mode: NULLABLE
  name: num_clients_active_on_day
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: num_clients_active_on_day
- mode: NULLABLE
  name: num_clients_dau_on_day
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: num_clients_dau_on_day
- mode: NULLABLE
  name: num_clients_active_atleastonce_in_last_7_days
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: num_clients_active_atleastonce_in_last_7_days
- mode: NULLABLE
  name: num_clients_active_atleastonce_in_last_28_days
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: num_clients_active_atleastonce_in_last_28_days
- mode: NULLABLE
  name: num_clients_repeat_first_month_users
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: num_clients_repeat_first_month_users
- mode: NULLABLE
  name: num_clients_dau_active_atleastonce_in_last_7_days
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: num_clients_dau_active_atleastonce_in_last_7_days
- mode: NULLABLE
  name: num_clients_dau_active_atleastonce_in_last_28_days
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: num_clients_dau_active_atleastonce_in_last_28_days
- mode: NULLABLE
  name: num_clients_dau_repeat_first_month_users
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: num_clients_dau_repeat_first_month_users
