fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/messaging_system_derived/messaging_system_derived.yaml
    field: submission_date
- name: release_channel
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/messaging_system_derived/messaging_system_derived.yaml
    field: release_channel
- name: country
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/messaging_system_derived/messaging_system_derived.yaml
    field: country
- name: country_name
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/messaging_system_derived/messaging_system_derived.yaml
    field: country_name
- name: locale
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/messaging_system_derived/messaging_system_derived.yaml
    field: locale
- name: version
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/messaging_system_derived/messaging_system_derived.yaml
    field: version
- name: mau
  type: INT64
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/messaging_system_derived/messaging_system_derived.yaml
    field: mau
- name: wau
  type: INT64
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/messaging_system_derived/messaging_system_derived.yaml
    field: wau
- name: dau
  type: INT64
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/messaging_system_derived/messaging_system_derived.yaml
    field: dau
- name: whats_new_mau
  type: INT64
  mode: NULLABLE
  description: The number of distinct CFR clients who were active in the What's New panel within the last 28 days of the submission date. Computed as
    a count of clients whose `days_since_seen_whats_new` is less than 28.
- name: whats_new_wau
  type: INT64
  mode: NULLABLE
  description: The number of distinct CFR clients who were active in the What's New panel within the last 7 days of the submission date. Computed as
    a count of clients whose `days_since_seen_whats_new` is less than 7.
- name: whats_new_dau
  type: INT64
  mode: NULLABLE
  description: The number of distinct CFR clients who were active in the What's New panel within the last 1 day of the submission date. Computed as a
    count of clients whose `days_since_seen_whats_new` is less than 1.
