fields:
  - mode: NULLABLE
    name: date
    type: DATE
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
      field: date
  - mode: NULLABLE
    name: category
    type: STRING
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
      field: category
  - mode: NULLABLE
    name: count
    type: INTEGER
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
      field: jsonPayload_fields_count
  - mode: NULLABLE
    name: usage
    type: FLOAT
  - mode: NULLABLE
    name: usage_unit
    type: STRING
  - mode: NULLABLE
    name: price
    type: FLOAT
  - mode: NULLABLE
    name: price_unit
    type: STRING
  - mode: NULLABLE
    name: description
    type: STRING
