fields:
- name: cdou
  type: INT64
  mode: NULLABLE
  description: ''
- name: cumulative_new_profiles
  type: INT64
  mode: NULLABLE
  description: ''
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: ''
- name: dau
  type: INT64
  mode: NULLABLE
  description: ''
- name: mau
  type: INT64
  mode: NULLABLE
  description: ''
- name: wau
  type: INT64
  mode: NULLABLE
  description: ''
- name: new_profiles
  type: INT64
  mode: NULLABLE
  description: ''
- name: submission_year
  type: INT64
  mode: NULLABLE
  description: ''
- name: id_bucket
  type: INT64
  mode: NULLABLE
  description: ''
- name: product
  type: STRING
  mode: NULLABLE
  description: ''
- name: normalized_channel
  type: STRING
  mode: NULLABLE
  description: ''
- name: campaign
  type: STRING
  mode: NULLABLE
  description: ''
- name: country
  type: STRING
  mode: NULLABLE
  description: ''
- name: distribution_id
  type: STRING
  mode: NULLABLE
  description: ''
