fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: ''
- name: aggregation_period
  type: STRING
  mode: NULLABLE
  description: ''
- name: source
  type: STRING
  mode: NULLABLE
  description: ''
- name: measure
  type: STRING
  mode: NULLABLE
  description: ''
- name: value
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: metric_alias
  type: STRING
  mode: NULLABLE
  description: ''
- name: metric_hub_app_name
  type: STRING
  mode: NULLABLE
  description: ''
- name: metric_hub_slug
  type: STRING
  mode: NULLABLE
  description: ''
- name: metric_start_date
  type: DATE
  mode: NULLABLE
  description: ''
- name: metric_end_date
  type: DATE
  mode: NULLABLE
  description: ''
- name: metric_collected_at
  type: TIMESTAMP
  mode: NULLABLE
  description: ''
- name: forecast_start_date
  type: DATE
  mode: NULLABLE
  description: ''
- name: forecast_end_date
  type: DATE
  mode: NULLABLE
  description: ''
- name: forecast_trained_at
  type: TIMESTAMP
  mode: NULLABLE
  description: ''
- name: forecast_predicted_at
  type: TIMESTAMP
  mode: NULLABLE
  description: ''
- name: forecast_parameters
  type: STRING
  mode: NULLABLE
  description: ''
