fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: submission_date
- mode: NULLABLE
  name: ping
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: ping
- mode: NULLABLE
  name: channel
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: channel
- mode: NULLABLE
  name: metric_name
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: metric_name
- mode: REPEATED
  name: percentiles
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: percentiles
- mode: NULLABLE
  name: mean
  type: FLOAT
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: mean
- mode: NULLABLE
  name: std_dev
  type: FLOAT
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: std_dev
- mode: NULLABLE
  name: median
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: median
