fields:
- mode: NULLABLE
  name: app_channel
  type: STRING
  description: App Channel
- mode: NULLABLE
  name: app_description
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: app_description
- mode: NULLABLE
  name: app_id
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: app_id
- mode: NULLABLE
  name: app_name
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: app_name
- mode: NULLABLE
  name: bq_dataset_family
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: bq_dataset_family
- mode: NULLABLE
  name: canonical_app_name
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: canonical_app_name
- mode: NULLABLE
  name: document_namespace
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: document_namespace
- mode: REPEATED
  name: notification_emails
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: notification_emails
- mode: NULLABLE
  name: url
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: url
- mode: NULLABLE
  name: v1_name
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: v1_name
- mode: NULLABLE
  name: is_glean
  type: BOOL
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: is_glean
