fields:
- name: slug
  type: STRING
  mode: NULLABLE
  description: ''
- name: app_name
  type: STRING
  mode: NULLABLE
  description: ''
- name: app_id
  type: STRING
  mode: NULLABLE
  description: ''
- name: start_date
  type: DATE
  mode: NULLABLE
  description: ''
- name: end_date
  type: DATE
  mode: NULLABLE
  description: ''
- name: status
  type: STRING
  mode: NULLABLE
  description: ''
- name: targeted_percent
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: targeting
  type: STRING
  mode: NULLABLE
  description: ''
- name: glean_metric_config
  type: JSON
  mode: NULLABLE
  description: ''
