fields:
- name: ds
  type: TIMESTAMP
  mode: NULLABLE
  description: ''
- name: trend
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: yhat_lower
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: yhat_upper
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: trend_lower
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: trend_upper
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: additive_terms
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: additive_terms_lower
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: additive_terms_upper
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: extra_regressors_additive
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: extra_regressors_additive_lower
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: extra_regressors_additive_upper
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: holidays
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: holidays_lower
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: holidays_upper
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: regressor_00
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: regressor_00_lower
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: regressor_00_upper
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: weekly
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: weekly_lower
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: weekly_upper
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: yearly
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: yearly_lower
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: yearly_upper
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: multiplicative_terms
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: multiplicative_terms_lower
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: multiplicative_terms_upper
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: yhat
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: target
  type: STRING
  mode: NULLABLE
  description: ''
- name: forecast_date
  type: STRING
  mode: NULLABLE
  description: ''
- name: forecast_parameters
  type: STRING
  mode: NULLABLE
  description: ''
- name: metric
  type: STRING
  mode: NULLABLE
  description: ''
