fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: ''
- name: dataset_id
  type: STRING
  mode: NULLABLE
  description: ''
- name: table_id
  type: STRING
  mode: NULLABLE
  description: ''
- name: byte_size
  type: INT64
  mode: NULLABLE
  description: ''
- name: row_count
  type: INT64
  mode: NULLABLE
  description: ''
