fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: submission_date

- mode: NULLABLE
  name: event_timestamp
  type: TIMESTAMP
  description: |
    Timestamp when the last recorded event
    took place. The date value for this field
    can be older or the same in comparison
    to submission_date.

- mode: NULLABLE
  name: user_id
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: user_id

- mode: NULLABLE
  name: service
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: jsonPayload_fields_service

- mode: NULLABLE
  name: device_id
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: jsonPayload_fields_device_id

- mode: NULLABLE
  name: os_name
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: jsonPayload_fields_os_name

- mode: NULLABLE
  name: flow_id
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: jsonPayload_fields_flow_id

- mode: NULLABLE
  name: event_type
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: jsonPayload_fields_event_type

- mode: NULLABLE
  name: country
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: country

- mode: NULLABLE
  name: language
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: jsonPayload_fields_context_language

- mode: NULLABLE
  name: entrypoint
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: entrypoint

- mode: NULLABLE
  name: utm_term
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: jsonPayload_fields_utm_term

- mode: NULLABLE
  name: utm_medium
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: jsonPayload_fields_utm_medium

- mode: NULLABLE
  name: utm_source
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: utm_source

- mode: NULLABLE
  name: utm_campaign
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: jsonPayload_fields_utm_campaign

- mode: NULLABLE
  name: utm_content
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: utm_content

- mode: NULLABLE
  name: ua_version
  type: STRING
  description: |
    The user's browser version.

- mode: NULLABLE
  name: ua_browser
  type: STRING
  description: |
    The user's web browser, e.g. 'Firefox' or 'Chrome'.

- mode: NULLABLE
  name: days_seen_bits
  type: INTEGER
  description: |
    Represents specific device's activity over the last 28 days.
    The rightmost bit represents whether the user was active
    in the current day.
