fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: ''
- name: product
  type: STRING
  mode: NULLABLE
  description: ''
- name: app_version
  type: STRING
  mode: NULLABLE
  description: ''
- name: os
  type: STRING
  mode: NULLABLE
  description: ''
- name: normalized_channel
  type: STRING
  mode: NULLABLE
  description: ''
- name: country
  type: STRING
  mode: NULLABLE
  description: ''
- name: new_profiles
  type: INT64
  mode: NULLABLE
  description: ''
- name: day_2_7_activated
  type: INT64
  mode: NULLABLE
  description: ''
