fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/addons_derived/dataset_schema.yaml
    field: submission_date

- name: client_id
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/addons_derived/dataset_schema.yaml
    field: client_id

- name: sample_id
  type: INTEGER
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/addons_derived/dataset_schema.yaml
    field: sample_id

- name: normalized_channel
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/addons_derived/dataset_schema.yaml
    field: normalized_channel

- name: app_version
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/addons_derived/dataset_schema.yaml
    field: app_version

- name: country
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/addons_derived/dataset_schema.yaml
    field: country

- name: locale
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/addons_derived/dataset_schema.yaml
    field: locale

- name: app_os
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/addons_derived/dataset_schema.yaml
    field: app_os

- name: addons
  type: RECORD
  mode: REPEATED
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/addons_derived/dataset_schema.yaml
    field: addons
  fields:
  - name: id
    type: STRING
    mode: NULLABLE
    description: |-
      Identifier of the active addon.
  - name: version
    type: STRING
    mode: NULLABLE
    description: |-
      Version of the active addon.
