fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/messaging_system_derived/messaging_system_derived.yaml
    field: submission_date
- name: days_seen_bits
  type: INTEGER
  mode: NULLABLE
- name: days_seen_whats_new_bits
  type: INTEGER
  mode: NULLABLE
  description: A 28-bit integer encoding the history of days on which the user was seen with the "What's New" panel over the past 28 days. Each bit position
    corresponds to one day, with the rightmost bit representing the current submission date; a set bit indicates the user had `seen_whats_new = true`
    on that day.
- name: impression_id
  type: STRING
  mode: NULLABLE
- name: client_id
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/messaging_system_derived/messaging_system_derived.yaml
    field: client_id
- name: seen_whats_new
  type: BOOLEAN
  mode: NULLABLE
- name: release_channel
  type: STRING
  mode: NULLABLE
- name: locale
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/messaging_system_derived/messaging_system_derived.yaml
    field: locale
- name: country
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/messaging_system_derived/messaging_system_derived.yaml
    field: country
- name: version
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/messaging_system_derived/messaging_system_derived.yaml
    field: version
