fields:
- mode: NULLABLE
  name: external_id
  type: STRING
  description: The unique identifier for the user in Braze, corresponding to the CTMS
    email_id UUID. Used to join to the subscriptions_map_v1 table to resolve Braze
    subscription group IDs.
- fields:
  - mode: NULLABLE
    name: subscription_name
    type: STRING
  - mode: NULLABLE
    name: firefox_subscription_id
    type: STRING
  - mode: NULLABLE
    name: mozilla_subscription_id
    type: STRING
  - mode: NULLABLE
    name: mozilla_dev_subscription_id
    type: STRING
  - mode: NULLABLE
    name: subscription_state
    type: STRING
  - mode: NULLABLE
    name: update_timestamp
    type: TIMESTAMP
  mode: REPEATED
  name: subscriptions
  type: RECORD
