fields:

- mode: NULLABLE
  name: first_seen_date
  type: DATE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: first_seen_date

- mode: NULLABLE
  name: user_id
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: user_id

- mode: NULLABLE
  name: country
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: country

- mode: NULLABLE
  name: language
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: language

- mode: NULLABLE
  name: os_name
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: os_name

- mode: NULLABLE
  name: os_version
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: os_version

- mode: NULLABLE
  name: seen_in_tier1_country
  type: BOOLEAN
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: seen_in_tier1_country

- mode: NULLABLE
  name: registered
  type: BOOLEAN
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: registered
