fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/addons_derived/dataset_schema.yaml
    field: submission_date
- name: hashed_addon_id
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/addons_derived/dataset_schema.yaml
    field: hashed_addon_id
- name: total_downloads
  type: INTEGER
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/addons_derived/dataset_schema.yaml
    field: total_downloads
- name: downloads_per_source
  type: RECORD
  mode: REPEATED
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/addons_derived/dataset_schema.yaml
    field: downloads_per_source
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
    description: Source name.
  - name: value
    type: INTEGER
    mode: NULLABLE
    description: Number of downloads attributed to the source.
- name: downloads_per_content
  type: RECORD
  mode: REPEATED
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/addons_derived/dataset_schema.yaml
    field: downloads_per_content
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
    description: Content name.
  - name: value
    type: INTEGER
    mode: NULLABLE
    description: Number of downloads attributed to the content.
- name: downloads_per_medium
  type: RECORD
  mode: REPEATED
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/addons_derived/dataset_schema.yaml
    field: downloads_per_medium
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
    description: Medium name.
  - name: value
    type: INTEGER
    mode: NULLABLE
    description: Number of downloads attributed to the medium.
- name: downloads_per_campaign
  type: RECORD
  mode: REPEATED
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/addons_derived/dataset_schema.yaml
    field: downloads_per_campaign
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
    description: Campaign name.
  - name: value
    type: INTEGER
    mode: NULLABLE
    description: Number of downloads attributed to the campaign.
- name: app
  type: STRING
  mode: NULLABLE
  description: For now always "Desktop".
