fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: !include-field-description
    file: /bigquery_etl/schema/firefoxdotcom_derived.yaml
    field: submission_date
- name: activity_date
  type: DATE
  mode: NULLABLE
  description: !include-field-description
    file: /bigquery_etl/schema/firefoxdotcom_derived.yaml
    field: activity_date
- name: fbclid
  type: STRING
  mode: NULLABLE
  description: A Facebook Click ID, which uniquely represent an ad impression for Google ads.
- name: ga_event_timestamp
  type: INT64
  mode: NULLABLE
  description: Earliest timestamp associated with the fbclid, might prove to be critical when formatting fbclid before sending to Conversions API.
- name: ga_country
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: /bigquery_etl/schema/firefoxdotcom_derived.yaml
    field: ga_country
- name: conversion_name
  type: STRING
  mode: NULLABLE
  description: Conversion name.
