fields:
  - mode: NULLABLE
    name: key
    type: STRING
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
      field: jsonPayload_fields_key
  - mode: NULLABLE
    name: permalink
    type: STRING
  - mode: NULLABLE
    name: id
    type: INTEGER
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
      field: jsonPayload_fields_id
  - mode: NULLABLE
    name: assignee
    type: STRING
  - mode: NULLABLE
    name: created
    type: TIMESTAMP
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
      field: jsonPayload_fields_created
  - mode: NULLABLE
    name: found_in
    type: STRING
  - mode: NULLABLE
    name: issuetype
    type: STRING
  - mode: NULLABLE
    name: reporter
    type: STRING
  - mode: NULLABLE
    name: resolution
    type: STRING
  - mode: NULLABLE
    name: resolutiondate
    type: TIMESTAMP
  - mode: NULLABLE
    name: status
    type: STRING
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
      field: jsonPayload_fields_status
  - mode: NULLABLE
    name: storypoints
    type: INTEGER
  - mode: NULLABLE
    name: summary
    type: STRING
  - mode: NULLABLE
    name: updated
    type: TIMESTAMP
  - mode: NULLABLE
    name: epic
    type: STRING
  - mode: NULLABLE
    name: originalstorypoints
    type: STRING
  - mode: NULLABLE
    name: timetoresolve
    type: INTEGER
  - mode: NULLABLE
    name: severity
    type: STRING
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
      field: severity
  - mode: NULLABLE
    name: priority
    type: STRING
  - mode: NULLABLE
    name: labels
    type: STRING
    description: !include-field-description
      file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
      field: resource_labels
  - mode: NULLABLE
    name: workcategory
    type: STRING
