fields:
- name: metric
  type: STRING
  mode: NULLABLE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: metric
- name: processes
  type: STRING
  mode: REPEATED
  description: ''
