fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: ''
- name: source
  type: STRING
  mode: NULLABLE
  description: ''
- name: min_timestamp
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: max_timestamp
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: up_to_date
  type: INT64
  mode: NULLABLE
  description: ''
- name: success
  type: INT64
  mode: NULLABLE
  description: ''
- name: backoff
  type: INT64
  mode: NULLABLE
  description: ''
- name: pref_disabled
  type: INT64
  mode: NULLABLE
  description: ''
- name: parse_error
  type: INT64
  mode: NULLABLE
  description: ''
- name: content_error
  type: INT64
  mode: NULLABLE
  description: ''
- name: sign_error
  type: INT64
  mode: NULLABLE
  description: ''
- name: sign_retry_error
  type: INT64
  mode: NULLABLE
  description: ''
- name: conflict_error
  type: INT64
  mode: NULLABLE
  description: ''
- name: sync_error
  type: INT64
  mode: NULLABLE
  description: ''
- name: apply_error
  type: INT64
  mode: NULLABLE
  description: ''
- name: server_error
  type: INT64
  mode: NULLABLE
  description: ''
- name: certificate_error
  type: INT64
  mode: NULLABLE
  description: ''
- name: download_error
  type: INT64
  mode: NULLABLE
  description: ''
- name: timeout_error
  type: INT64
  mode: NULLABLE
  description: ''
- name: network_error
  type: INT64
  mode: NULLABLE
  description: ''
- name: offline_error
  type: INT64
  mode: NULLABLE
  description: ''
- name: cleanup_error
  type: INT64
  mode: NULLABLE
  description: ''
- name: unknown_error
  type: INT64
  mode: NULLABLE
  description: ''
- name: custom_1_error
  type: INT64
  mode: NULLABLE
  description: ''
- name: custom_2_error
  type: INT64
  mode: NULLABLE
  description: ''
- name: custom_3_error
  type: INT64
  mode: NULLABLE
  description: ''
- name: custom_4_error
  type: INT64
  mode: NULLABLE
  description: ''
- name: custom_5_error
  type: INT64
  mode: NULLABLE
  description: ''
