fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: submission_date
- mode: NULLABLE
  name: app_version
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: app_version
- mode: NULLABLE
  name: country
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: country
- mode: NULLABLE
  name: normalized_os
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: normalized_os
- mode: NULLABLE
  name: channel
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: channel
- mode: NULLABLE
  name: locale
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: top_locales_locale
- mode: NULLABLE
  name: profile_creation_month
  type: DATE
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: profile_creation_month
- mode: NULLABLE
  name: default_search_engine
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: default_search_engine
- mode: NULLABLE
  name: is_default_browser
  type: BOOLEAN
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: is_default_browser
- mode: NULLABLE
  name: is_sap_monetizable
  type: BOOLEAN
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: is_sap_monetizable
- mode: NULLABLE
  name: has_adblocker_addon
  type: BOOLEAN
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: has_adblocker_addon
- mode: NULLABLE
  name: policies_is_enterprise
  type: BOOLEAN
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: policies_is_enterprise
- mode: NULLABLE
  name: stories_enabled
  type: BOOLEAN
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: stories_enabled
- mode: NULLABLE
  name: sponsored_stories_enabled
  type: BOOLEAN
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: sponsored_stories_enabled
- mode: NULLABLE
  name: topsites_enabled
  type: BOOLEAN
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: topsites_enabled
- mode: NULLABLE
  name: sponsored_topsites_enabled
  type: BOOLEAN
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: sponsored_topsites_enabled
- mode: NULLABLE
  name: topic_preferences_set
  type: BOOLEAN
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: topic_preferences_set
- mode: NULLABLE
  name: client_count
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: client_count
- mode: NULLABLE
  name: clients_with_newtab_and_search_activity
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: clients_with_newtab_and_search_activity
- mode: NULLABLE
  name: clients_with_ad_engagement
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: clients_with_ad_engagement
- mode: NULLABLE
  name: clients_with_search_ad_engagement
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: clients_with_search_ad_engagement
- mode: NULLABLE
  name: clients_with_newtab_ad_engagement
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: clients_with_newtab_ad_engagement
- mode: NULLABLE
  name: subsession_hours_sum_total
  type: FLOAT
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: subsession_hours_sum_total
- mode: REPEATED
  name: subsession_hours_sum_histogram
  type: FLOAT
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: subsession_hours_sum_histogram
- mode: NULLABLE
  name: sessions_started_on_this_day_total
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: sessions_started_on_this_day_total
- mode: REPEATED
  name: sessions_started_on_this_day_histogram
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: sessions_started_on_this_day_histogram
- mode: REPEATED
  name: active_addons_count_mean_histogram
  type: FLOAT
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: active_addons_count_mean_histogram
- mode: REPEATED
  name: max_concurrent_tab_count_max_histogram
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: max_concurrent_tab_count_max_histogram
- mode: REPEATED
  name: active_hours_sum_histogram
  type: FLOAT
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: active_hours_sum_histogram
- mode: REPEATED
  name: total_uri_count_histogram
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: total_uri_count_histogram
- mode: NULLABLE
  name: organic_sum
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: organic_sum
- mode: REPEATED
  name: organic_histogram
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: organic_histogram
- mode: NULLABLE
  name: tagged_sap_sum
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: tagged_sap_sum
- mode: REPEATED
  name: tagged_sap_histogram
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: tagged_sap_histogram
- mode: NULLABLE
  name: tagged_follow_on_sum
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: tagged_follow_on_sum
- mode: REPEATED
  name: tagged_follow_on_histogram
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: tagged_follow_on_histogram
- mode: NULLABLE
  name: sap_sum
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: sap_sum
- mode: REPEATED
  name: sap_histogram
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: sap_histogram
- mode: NULLABLE
  name: ad_click_sum
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: ad_click_sum
- mode: REPEATED
  name: ad_click_histogram
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: ad_click_histogram
- mode: NULLABLE
  name: ad_click_organic_sum
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: ad_click_organic_sum
- mode: REPEATED
  name: ad_click_organic_histogram
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: ad_click_organic_histogram
- mode: NULLABLE
  name: search_with_ads_sum
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: search_with_ads_sum
- mode: REPEATED
  name: search_with_ads_histogram
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: search_with_ads_histogram
- mode: NULLABLE
  name: newtab_visit_count_sum
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: newtab_visit_count_sum
- mode: REPEATED
  name: newtab_visit_count_histogram
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: newtab_visit_count_histogram
- mode: NULLABLE
  name: visits_with_non_search_engagement_sum
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: visits_with_non_search_engagement_sum
- mode: REPEATED
  name: visits_with_non_search_engagement_histogram
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: visits_with_non_search_engagement_histogram
- mode: NULLABLE
  name: organic_topsite_tile_clicks_sum
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: organic_topsite_tile_clicks_sum
- mode: REPEATED
  name: organic_topsite_tile_clicks_histogram
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: organic_topsite_tile_clicks_histogram
- mode: NULLABLE
  name: sponsored_topsite_tile_clicks_sum
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: sponsored_topsite_tile_clicks_sum
- mode: REPEATED
  name: sponsored_topsite_tile_clicks_histogram
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: sponsored_topsite_tile_clicks_histogram
- mode: NULLABLE
  name: organic_topsite_tile_impressions_sum
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: organic_topsite_tile_impressions_sum
- mode: REPEATED
  name: organic_topsite_tile_impressions_histogram
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: organic_topsite_tile_impressions_histogram
- mode: NULLABLE
  name: sponsored_topsite_tile_impressions_sum
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: sponsored_topsite_tile_impressions_sum
- mode: REPEATED
  name: sponsored_topsite_tile_impressions_histogram
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: sponsored_topsite_tile_impressions_histogram
- mode: NULLABLE
  name: organic_topsite_tile_dismissals_sum
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: organic_topsite_tile_dismissals_sum
- mode: REPEATED
  name: organic_topsite_tile_dismissals_histogram
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: organic_topsite_tile_dismissals_histogram
- mode: NULLABLE
  name: sponsored_topsite_tile_dismissals_sum
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: sponsored_topsite_tile_dismissals_sum
- mode: REPEATED
  name: sponsored_topsite_tile_dismissals_histogram
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: sponsored_topsite_tile_dismissals_histogram
- mode: NULLABLE
  name: organic_stories_impressions_sum
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: organic_stories_impressions_sum
- mode: REPEATED
  name: organic_stories_impressions_histogram
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: organic_stories_impressions_histogram
- mode: NULLABLE
  name: sponsored_stories_impressions_sum
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: sponsored_stories_impressions_sum
- mode: REPEATED
  name: sponsored_stories_impressions_histogram
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: sponsored_stories_impressions_histogram
- mode: NULLABLE
  name: organic_stories_clicks_sum
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: organic_stories_clicks_sum
- mode: REPEATED
  name: organic_stories_clicks_histogram
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: organic_stories_clicks_histogram
- mode: NULLABLE
  name: sponsored_stories_clicks_sum
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: sponsored_stories_clicks_sum
- mode: REPEATED
  name: sponsored_stories_clicks_histogram
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: sponsored_stories_clicks_histogram
- mode: NULLABLE
  name: organic_stories_dismissals_sum
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: organic_stories_dismissals_sum
- mode: REPEATED
  name: organic_stories_dismissals_histogram
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: organic_stories_dismissals_histogram
- mode: NULLABLE
  name: sponsored_stories_dismissals_sum
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: sponsored_stories_dismissals_sum
- mode: REPEATED
  name: sponsored_stories_dismissals_histogram
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/telemetry_derived/telemetry_derived.yaml
    field: sponsored_stories_dismissals_histogram
