fields:
- mode: NULLABLE
  name: tile_id
  type: INTEGER
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/pocket_derived/pocket_derived.yaml
    field: tile_id
- mode: NULLABLE
  name: type
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/pocket_derived/pocket_derived.yaml
    field: type
