fields:

- mode: NULLABLE
  name: first_seen_date
  type: TIMESTAMP
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: first_seen_date

- mode: NULLABLE
  name: flow_id
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: flow_id

- mode: NULLABLE
  name: user_id
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: user_id

- mode: NULLABLE
  name: service
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: service

- mode: NULLABLE
  name: device_id
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: device_id

- mode: NULLABLE
  name: event_type
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: event_type

- mode: NULLABLE
  name: os_name
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: os_name

- mode: NULLABLE
  name: country
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: country

- mode: NULLABLE
  name: language
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: language

- mode: NULLABLE
  name: entrypoint
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: entrypoint

- mode: NULLABLE
  name: utm_term
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: utm_term

- mode: NULLABLE
  name: utm_medium
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: utm_medium

- mode: NULLABLE
  name: utm_source
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: utm_source

- mode: NULLABLE
  name: utm_campaign
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: utm_campaign

- mode: NULLABLE
  name: utm_content
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: utm_content

- mode: NULLABLE
  name: ua_version
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: ua_version

- mode: NULLABLE
  name: ua_browser
  type: STRING
  description: !include-field-description
    file: sql/moz-fx-data-shared-prod/firefox_accounts_derived/firefox_accounts_derived.yaml
    field: ua_browser
