fields:
- name: key
  type: STRING
  mode: NULLABLE
  description: ''
- name: submission_date
  type: TIMESTAMP
  mode: NULLABLE
  description: ''
- name: dau_forecast
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: dau_target
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: cdou_forecast
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: cdou_target
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: dau_forecast_lower
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: dau_forecast_upper
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: new_profiles_forecast
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: new_profiles_target
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: cum_new_profiles_forecast
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: cum_new_profiles_target
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: new_profiles_forecast_lower
  type: FLOAT64
  mode: NULLABLE
  description: ''
- name: new_profiles_forecast_upper
  type: FLOAT64
  mode: NULLABLE
  description: ''
